# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34d8dfb50f9dc71b801cabd52395f5ea437c6b4054c9c65f911f1f729f86449abf85ffa2b41d61bad8be189e0e42080dfdaf1e5d96894c6c187176ac645f4296

test:
  secret_key_base: 075d5af6da1c5701c833a2443f97faa8625c991fca87478a9b56c4ccfba535449d0c75fe84d36a121798d604e22675d8e24be179c90244c6cce7dfe1e3492064

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
